version: "3.7"

networks:
  skeleton:

services:
  nginx:
    image: nginx:alpine
    container_name: ${APPLICATION_NAME}-nginx-webserver
    working_dir: /application
    depends_on:
      - php-fpm
      - mysql
    volumes:
      - .:/application
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HTTP_PORT}:80"
    networks:
      skeleton:

  php-fpm:
    build: "./docker"
    container_name: ${APPLICATION_NAME}-php-fpm
    working_dir: /application
    tty: true
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      skeleton:

  mysql:
    image: mysql:8.0
    container_name: ${APPLICATION_NAME}-mysql
    working_dir: /application
    tty: true
    volumes:
      - .:/application
    environment:
      MYSQL_ROOT_PASSWORD: $${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: $${MYSQL_DATABASE}
      MYSQL_USER: $${MYSQL_USER}
      MYSQL_PASSWORD: $${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    networks:
      skeleton:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APPLICATION_NAME}-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: $${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    tty: false
    networks:
      skeleton:
