version: "3.7"

networks:
  skeleton:

services:
    mysql:
      image: mysql:8.0
      container_name: mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=skeletondb
        - MYSQL_USER=skeleton
        - MYSQL_PASSWORD=root
      ports:
        - "8090:3306"
      networks:
        skeleton:

    nginx:
      image: nginx:alpine
      container_name: nginx-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8088:80"
      networks:
        skeleton:

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
        skeleton:

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      depends_on:
        - mysql
      ports:
        - "8089:80"
      environment:
        PMA_HOST: mysql
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
      tty: false
      restart: always
      networks:
        skeleton:
