version: "3.7"

networks:
  skeleton:

services:
  nginx:
    image: nginx:alpine
    container_name: ${APPLICATION_NAME}-nginx
    working_dir: /application
    depends_on:
      - php-fpm
      - mysql
    volumes:
      - .:/application
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HTTP_PORT}:80"
    networks:
      skeleton:

  php-fpm:
    build: "./docker"
    container_name: ${APPLICATION_NAME}-phpfpm
    working_dir: /application
    tty: true
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - ./docker/php/logs/errors.log:/var/log/php-fpm/errors.log
    networks:
      skeleton:

  mysql:
    image: mysql:latest
    container_name: ${APPLICATION_NAME}-mysql
    working_dir: /application
    tty: true
    volumes:
      - .:/application
      - ./docker/mysql/mysql-data:/var/lib/mysql
      - ./docker/mysql/logs/mysqld.log:/var/log/mysqld.log
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    networks:
      skeleton:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APPLICATION_NAME}-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${APPLICATION_NAME}-mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    tty: false
    networks:
      skeleton:
