version: "3"

networks:
  skeleton:

services:
  nginx:
    image: nginx:alpine
    container_name: skeleton-nginx-webserver
    working_dir: /application
    env_file:
      - ".env.docker"
    depends_on:
      - php-fpm
      - mysql
    volumes:
      - .:/application
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      skeleton:

  php-fpm:
    build: ""
    container_name: skeleton-php-fpm
    working_dir: /application
    env_file:
      - ".env.docker"
    tty: true
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      skeleton:

  mysql:
    image: mysql:8.0
    container_name: skeleton-mysql
    working_dir: /application
    tty: true
    env_file:
      - ".env.docker"
    volumes:
      - .:/application
    environment:
      MYSQL_ROOT_PASSWORD: $${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: $${MYSQL_DATABASE}
      MYSQL_USER: $${MYSQL_USER}
      MYSQL_PASSWORD: $${MYSQL_PASSWORD}
    ports:
      - "4306:3306"
    restart: always
    networks:
      skeleton:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: skeleton-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: $${MYSQL_ROOT_PASSWORD}
    ports:
      - "9000:80"
    tty: false
    networks:
      skeleton:
